// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func BuildClient() *Client {
	serviceFoo := NewFoo()
	serviceBar := NewBar()
	client := NewClient(serviceFoo, serviceBar)
	return client
}
