// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/test.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//性别
type Sex int32

const (
	Sex_MAN   Sex = 0
	Sex_WOMAN Sex = 1
)

var Sex_name = map[int32]string{
	0: "MAN",
	1: "WOMAN",
}

var Sex_value = map[string]int32{
	"MAN":   0,
	"WOMAN": 1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}

func (Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dff63324815cff01, []int{0}
}

// 班级
type Class struct {
	Num                  int32      `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Students             []*Student `protobuf:"bytes,2,rep,name=students,proto3" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff63324815cff01, []int{0}
}

func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Class) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

// 学生
type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  Sex      `protobuf:"varint,3,opt,name=sex,proto3,enum=pb.Sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff63324815cff01, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MAN
}

type Example1 struct {
	StringVal            string                    `protobuf:"bytes,1,opt,name=stringVal,proto3" json:"stringVal,omitempty"`
	BytesVal             []byte                    `protobuf:"bytes,2,opt,name=bytesVal,proto3" json:"bytesVal,omitempty"`
	EmbeddedExample1     *Example1_EmbeddedMessage `protobuf:"bytes,3,opt,name=embeddedExample1,proto3" json:"embeddedExample1,omitempty"`
	RepeatedInt32Val     []int32                   `protobuf:"varint,4,rep,packed,name=repeatedInt32Val,proto3" json:"repeatedInt32Val,omitempty"`
	RepeatedStringVal    []string                  `protobuf:"bytes,5,rep,name=repeatedStringVal,proto3" json:"repeatedStringVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Example1) Reset()         { *m = Example1{} }
func (m *Example1) String() string { return proto.CompactTextString(m) }
func (*Example1) ProtoMessage()    {}
func (*Example1) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff63324815cff01, []int{2}
}

func (m *Example1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example1.Unmarshal(m, b)
}
func (m *Example1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example1.Marshal(b, m, deterministic)
}
func (m *Example1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example1.Merge(m, src)
}
func (m *Example1) XXX_Size() int {
	return xxx_messageInfo_Example1.Size(m)
}
func (m *Example1) XXX_DiscardUnknown() {
	xxx_messageInfo_Example1.DiscardUnknown(m)
}

var xxx_messageInfo_Example1 proto.InternalMessageInfo

func (m *Example1) GetStringVal() string {
	if m != nil {
		return m.StringVal
	}
	return ""
}

func (m *Example1) GetBytesVal() []byte {
	if m != nil {
		return m.BytesVal
	}
	return nil
}

func (m *Example1) GetEmbeddedExample1() *Example1_EmbeddedMessage {
	if m != nil {
		return m.EmbeddedExample1
	}
	return nil
}

func (m *Example1) GetRepeatedInt32Val() []int32 {
	if m != nil {
		return m.RepeatedInt32Val
	}
	return nil
}

func (m *Example1) GetRepeatedStringVal() []string {
	if m != nil {
		return m.RepeatedStringVal
	}
	return nil
}

type Example1_EmbeddedMessage struct {
	Int32Val             int32    `protobuf:"varint,1,opt,name=int32Val,proto3" json:"int32Val,omitempty"`
	StringVal            string   `protobuf:"bytes,2,opt,name=stringVal,proto3" json:"stringVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Example1_EmbeddedMessage) Reset()         { *m = Example1_EmbeddedMessage{} }
func (m *Example1_EmbeddedMessage) String() string { return proto.CompactTextString(m) }
func (*Example1_EmbeddedMessage) ProtoMessage()    {}
func (*Example1_EmbeddedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff63324815cff01, []int{2, 0}
}

func (m *Example1_EmbeddedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example1_EmbeddedMessage.Unmarshal(m, b)
}
func (m *Example1_EmbeddedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example1_EmbeddedMessage.Marshal(b, m, deterministic)
}
func (m *Example1_EmbeddedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example1_EmbeddedMessage.Merge(m, src)
}
func (m *Example1_EmbeddedMessage) XXX_Size() int {
	return xxx_messageInfo_Example1_EmbeddedMessage.Size(m)
}
func (m *Example1_EmbeddedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Example1_EmbeddedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Example1_EmbeddedMessage proto.InternalMessageInfo

func (m *Example1_EmbeddedMessage) GetInt32Val() int32 {
	if m != nil {
		return m.Int32Val
	}
	return 0
}

func (m *Example1_EmbeddedMessage) GetStringVal() string {
	if m != nil {
		return m.StringVal
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Sex", Sex_name, Sex_value)
	proto.RegisterType((*Class)(nil), "pb.Class")
	proto.RegisterType((*Student)(nil), "pb.Student")
	proto.RegisterType((*Example1)(nil), "pb.Example1")
	proto.RegisterType((*Example1_EmbeddedMessage)(nil), "pb.Example1.EmbeddedMessage")
}

func init() { proto.RegisterFile("pb/test.proto", fileDescriptor_dff63324815cff01) }

var fileDescriptor_dff63324815cff01 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdd, 0x6a, 0xb3, 0x40,
	0x10, 0x86, 0x3f, 0xdd, 0xf8, 0x25, 0x4e, 0xfa, 0x63, 0xe7, 0xc8, 0x84, 0x1c, 0x48, 0x4e, 0x2a,
	0xa1, 0x58, 0x6a, 0xae, 0xa0, 0x2d, 0x81, 0xfe, 0x90, 0x16, 0x36, 0xd0, 0x1e, 0xef, 0xe2, 0x20,
	0x81, 0x68, 0x96, 0xec, 0x06, 0xec, 0x85, 0xf5, 0xfe, 0xca, 0x9a, 0x68, 0x69, 0x3c, 0x9b, 0x79,
	0x46, 0x9f, 0x57, 0x67, 0xe0, 0x5c, 0xc9, 0x5b, 0x43, 0xda, 0x24, 0x6a, 0xb7, 0x35, 0x5b, 0x74,
	0x95, 0x9c, 0x3e, 0x80, 0xf7, 0xb8, 0x11, 0x5a, 0x63, 0x00, 0xac, 0xdc, 0x17, 0xa1, 0x13, 0x39,
	0xb1, 0xc7, 0x6d, 0x89, 0xd7, 0x30, 0xd0, 0x66, 0x9f, 0x51, 0x69, 0x74, 0xe8, 0x46, 0x2c, 0x1e,
	0xa6, 0xc3, 0x44, 0xc9, 0x64, 0x75, 0x60, 0xbc, 0x1d, 0x4e, 0x5f, 0xa0, 0x7f, 0x84, 0x88, 0xd0,
	0x2b, 0x45, 0x41, 0xb5, 0xc6, 0xe7, 0x75, 0x6d, 0xcd, 0x22, 0xa7, 0xd0, 0x3d, 0x98, 0x45, 0x4e,
	0x38, 0x02, 0xa6, 0xa9, 0x0a, 0x59, 0xe4, 0xc4, 0x17, 0x69, 0xbf, 0x96, 0x52, 0xc5, 0x2d, 0x9b,
	0x7e, 0xbb, 0x30, 0x58, 0x54, 0xa2, 0x50, 0x1b, 0xba, 0xc3, 0x09, 0xf8, 0xda, 0xec, 0xd6, 0x65,
	0xfe, 0x21, 0x36, 0x47, 0xe5, 0x2f, 0xc0, 0x31, 0x0c, 0xe4, 0x97, 0x21, 0x6d, 0x87, 0x56, 0x7e,
	0xc6, 0xdb, 0x1e, 0x9f, 0x20, 0xa0, 0x42, 0x52, 0x96, 0x51, 0xd6, 0xd8, 0xea, 0xb8, 0x61, 0x3a,
	0xb1, 0x71, 0x0d, 0x4b, 0x16, 0xc7, 0x87, 0x96, 0xa4, 0xb5, 0xc8, 0x89, 0x77, 0xde, 0xc2, 0x19,
	0x04, 0x3b, 0x52, 0x24, 0x0c, 0x65, 0xcf, 0xa5, 0x99, 0xa7, 0x36, 0xad, 0x17, 0xb1, 0xd8, 0xe3,
	0x1d, 0x8e, 0x37, 0x70, 0xd5, 0xb0, 0x55, 0xfb, 0xdd, 0x5e, 0xc4, 0x62, 0x9f, 0x77, 0x07, 0xe3,
	0x57, 0xb8, 0x3c, 0x89, 0xb7, 0xbf, 0xb4, 0x6e, 0x42, 0x0e, 0x97, 0x68, 0xfb, 0xbf, 0xcb, 0x70,
	0x4f, 0x96, 0x31, 0x1b, 0x01, 0x5b, 0x51, 0x85, 0x7d, 0x60, 0xcb, 0xfb, 0xb7, 0xe0, 0x1f, 0xfa,
	0xe0, 0x7d, 0xbe, 0xdb, 0xd2, 0x91, 0xff, 0xeb, 0x6b, 0xcf, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xeb, 0xbb, 0xba, 0x8f, 0xfe, 0x01, 0x00, 0x00,
}
